### ISSUE TITLE
Feedback for “NGINX va NGINX Plus-ni web-server sifatida sozlash”

### ISSUE THREAD

**Issue by eugene0928** [ismoilovdevml/devops-journey#14]
`http` context va `proxy directives` lar haqida kopro malumot berilsa yaxshi bolardi.

**Comment by ismoilovdevml** [comment]
Feedback uchuh raxmat bu mavzu oxirigacha yetmay qolgandi ming bor uzur )

**Comment by eugene0928** [comment]
Qaysi manbadan foydalangansz, ağar imkonim bolsa yordamlashardim.

Juda ham foydali ish qilyapsz

**Comment by ismoilovdevml** [comment]
Nginx o'zining dokumentatsiyalaridan va o'zimdan )
https://docs.nginx.com/nginx/admin-guide/web-server/web-server/
