### ISSUE TITLE
i18n notog'ri setup qilingan

### ISSUE THREAD

**Issue by ShukhratbekDev** [ismoilovdevml/devops-journey#16]
`en-UZ` locale yo'q standartda. Shuni `uz` qilib qo'ysa yaxshi bo'ladi.
<img width="322" alt="image" src="https://github.com/ismoilovdevml/devops-journey/assets/159551353/0e628a1c-1451-44f2-9083-3f6ee8a8ddd9">

https://www.unicode.org/reports/tr35/tr35-59/tr35.html#Identifiers

**Comment by ismoilovdevml** [comment]
![image](https://github.com/ismoilovdevml/devops-journey/assets/107093598/ea885ef6-550e-4571-bb25-17bf87cae8d6)
uz-UZ qilamizmi

**Comment by ismoilovdevml** [comment]
O'zingiz bir loyihaga contibutorlik qilib yordam qilmesizmi :)

**Comment by mrmuminov** [comment]
@ismoilovdevml ha https://www.w3schools.com/tags/ref_language_codes.asp bu ko'rinishda qilganingiz yaxshiroq menimcha.
