### ISSUE TITLE
CONTRIBUTING.md fileda xatolik

### ISSUE THREAD

**Issue by sanjarDev1** [ismoilovdevml/devops-journey#17]
![20240314_001045](https://github.com/ismoilovdevml/devops-journey/assets/88580441/82f549a7-b889-410b-85c1-19a7a740dae7)
Pull request bolish kerak edi

**Comment by ismoilovdevml** [comment]
Xatolik to'grilandi 
https://github.com/ismoilovdevml/devops-journey/commit/5131ff5586865445b6da2eaaebf51d0ffd5b67fb#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055
