### ISSUE TITLE
Found broken `/tutorials/article/gnp-monitoring#prometheus-nima` link. Please fix!

### ISSUE THREAD

**Issue by imsdkl** [ismoilovdevml/devops-journey#20]
https://devops-journey.uz/guides/database/postgres-monitoring
topicdagi quyidagi havolalar ishlamayapti!

![image](https://github.com/user-attachments/assets/635978c7-620d-46dd-be74-27b3606a3184)

**Comment by ismoilovdevml** [comment]
hozir to'grilaymiz

**Comment by ismoilovdevml** [comment]
to'grilandi sizga raxmat )
