### ISSUE TITLE
Found broken `/guides/database/create-a-livestream` link. Please fix!

### ISSUE THREAD

**Issue by foxdevuz** [ismoilovdevml/devops-journey#3]

**Comment by ismoilovdevml** [comment]
bug fixed

**Comment by foxdevuz** [comment]
404 - Siz bu yerlarda nimalar qilib yuribsiz?))
Shunaqa xatolik olyapman :(
![image](https://github.com/ismoilovdevml/devops-journey/assets/86303222/6d9f079d-e24a-4a7d-9b65-0b5fb2459da0)

[URL](https://devops-journey.uz/guides/database/create-a-livestream)

**Comment by ismoilovdevml** [comment]
qaysi pageda chiqyapti bu qayerda muammo
bu muammolar allaqachon to'grilangan

**Comment by foxdevuz** [comment]
o'sha pagega adashib kirib qolganmanda aniq titlesi esimda yo'q.😢
